"""
Payment Gateway Routes — Production-Grade Razorpay Integration
=================================================================
Handles:
- Razorpay order creation (POST /payments/create-order)
- Cryptographic HMAC-SHA256 signature verification (POST /payments/verify)
- Webhook events listener (POST /payments/webhook)
- Refund processing (POST /payments/refund/{payment_id})
- Transaction history & audit log (GET /payments/history, GET /payments/{payment_id})
"""

from fastapi import APIRouter, HTTPException, Depends, Request, Header
from bson import ObjectId
from datetime import datetime
from typing import Optional, Dict, Any, List
import razorpay
import random
import pymongo

from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import jwt
from pydantic import BaseModel, Field
from app.config import settings
from app.auth_utils import verify_token
from app.database import get_db

router = APIRouter(prefix="/payments", tags=["Payment Gateway Engine (Razorpay)"])

optional_security = HTTPBearer(auto_error=False)

def get_optional_user(credentials: Optional[HTTPAuthorizationCredentials] = Depends(optional_security)) -> dict:
    """Extract user payload if valid token provided, else fallback gracefully without throwing 401."""
    if credentials and credentials.credentials:
        try:
            payload = jwt.decode(credentials.credentials, settings.JWT_SECRET_KEY, algorithms=[settings.ALGORITHM])
            return payload
        except Exception:
            pass
    return {"sub": "650000000000000000000001", "email": "patient@sehatsathi.com", "name": "Patient", "role": "Patient"}

# Initialize Razorpay Client singleton
def get_razorpay_client():
    return razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))


# ─────────────────────────────────────────────────────────────
# REQUEST & RESPONSE SCHEMAS
# ─────────────────────────────────────────────────────────────

class CreateOrderRequest(BaseModel):
    amount: float = Field(..., gt=0, description="Amount in INR")
    currency: Optional[str] = Field("INR", description="Currency code (e.g. INR)")
    booking_type: str = Field(default="appointment", description="'appointment' | 'room' | 'lab'")
    notes: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Metadata notes for Razorpay Order")


class VerifyPaymentRequest(BaseModel):
    razorpay_order_id: str = Field(..., description="Order ID generated by Razorpay")
    razorpay_payment_id: str = Field(..., description="Payment ID generated by Razorpay Checkout")
    razorpay_signature: str = Field(..., description="Cryptographic HMAC-SHA256 signature from Razorpay")
    booking_type: Optional[str] = Field("appointment", description="'appointment' | 'room' | 'lab'")
    booking_payload: Dict[str, Any] = Field(..., description="Booking information to commit upon successful payment verification")


class RefundRequest(BaseModel):
    amount: Optional[float] = Field(None, description="Optional partial refund amount in INR. Omit for full refund.")
    reason: Optional[str] = Field("Patient Requested Refund / Cancellation", description="Reason for refund")


# ── Internal Notification Helper ──
async def _notify(db: Any, user_id: str, notif_type: str, title: str, message: str, metadata: Optional[Dict[str, Any]] = None) -> None:
    try:
        await db["notifications"].insert_one({
            "user_id": user_id,
            "type": notif_type,
            "title": title,
            "message": message,
            "is_read": False,
            "metadata": metadata or {},
            "created_at": datetime.now(),
        })
    except Exception:
        pass


# ─────────────────────────────────────────────────────────────
# 1. CREATE RAZORPAY ORDER
# ─────────────────────────────────────────────────────────────

@router.post("/create-order")
async def create_payment_order(
    req: CreateOrderRequest,
    current_user: dict = Depends(get_optional_user)
):
    """
    Creates an official Razorpay Order ID via Python SDK.
    Stores a pending transaction record in MongoDB payments collection.
    """
    db = get_db()
    user_id = current_user.get("sub")
    client = get_razorpay_client()

    amount_in_paise = int(round(req.amount * 100))

    try:
        # Call Razorpay Python SDK to create order
        razorpay_order = client.order.create({
            "amount": amount_in_paise,
            "currency": req.currency or "INR",
            "receipt": f"rcpt_{int(datetime.now().timestamp() * 1000)}",
            "notes": {
                "user_id": user_id,
                "booking_type": req.booking_type,
                **(req.notes or {})
            }
        })
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Razorpay Order Creation Failed: {str(e)}")

    order_id = razorpay_order["id"]

    # Store pending payment in MongoDB
    payment_doc = {
        "order_id": order_id,
        "payment_id": None,
        "user_id": user_id,
        "booking_type": req.booking_type,
        "amount": req.amount,
        "amount_paise": amount_in_paise,
        "currency": req.currency or "INR",
        "status": "created",
        "payment_method": None,
        "gateway": "razorpay",
        "notes": req.notes or {},
        "signature": None,
        "invoice_id": None,
        "created_at": datetime.now(),
        "updated_at": datetime.now()
    }

    await db["payments"].insert_one(payment_doc)

    return {
        "success": True,
        "order_id": order_id,
        "amount": razorpay_order["amount"],
        "currency": razorpay_order["currency"],
        "key_id": settings.RAZORPAY_KEY_ID
    }


# ─────────────────────────────────────────────────────────────
# 2. VERIFY RAZORPAY PAYMENT SIGNATURE & CONFIRM BOOKING
# ─────────────────────────────────────────────────────────────

@router.post("/verify")
async def verify_payment_and_confirm(
    req: VerifyPaymentRequest,
    current_user: dict = Depends(get_optional_user)
):
    """
    Backend ONLY Cryptographic Payment Verification.
    Verifies razorpay_order_id, razorpay_payment_id, and razorpay_signature using HMAC-SHA256.
    Commits the appointment/room/lab booking, generates GST invoice, and dispatches notifications.
    """
    db = get_db()
    user_id = current_user.get("sub")
    client = get_razorpay_client()

    # 1. Cryptographic HMAC-SHA256 Signature Verification
    try:
        client.utility.verify_payment_signature({
            'razorpay_order_id': req.razorpay_order_id,
            'razorpay_payment_id': req.razorpay_payment_id,
            'razorpay_signature': req.razorpay_signature
        })
    except Exception:
        # Signature mismatch or tampering
        raise HTTPException(
            status_code=400,
            detail="Payment verification failed: Invalid Razorpay cryptographic signature."
        )

    # 2. Fetch Payment details from Razorpay to get method (UPI, Card, NetBanking, etc.)
    payment_method_name = "UPI"
    try:
        rzp_payment = client.payment.fetch(req.razorpay_payment_id)
        raw_method = rzp_payment.get("method", "upi")
        payment_method_name = raw_method.upper()
    except Exception:
        pass

    # 3. Update payment document in MongoDB to 'captured'
    await db["payments"].update_one(
        {"order_id": req.razorpay_order_id},
        {"$set": {
            "payment_id": req.razorpay_payment_id,
            "signature": req.razorpay_signature,
            "status": "captured",
            "payment_method": payment_method_name,
            "updated_at": datetime.now()
        }},
        upsert=True
    )

    payload = req.booking_payload or {}
    booking_type = req.booking_type or "appointment"

    created_booking_id = None
    created_invoice_doc = None

    # 4. COMMIT BOOKING & GENERATE INVOICE BASED ON TYPE
    if booking_type == "appointment":
        # Check double booking
        doctor_id = payload.get("doctor_id")
        date_str = payload.get("date")
        slot_str = payload.get("time_slot")

        existing = await db["appointments"].find_one({
            "doctor_id": doctor_id,
            "date": date_str,
            "time_slot": slot_str,
            "status": {"$ne": "Cancelled"}
        })
        if existing:
            raise HTTPException(
                status_code=400,
                detail="This time slot was taken during checkout. Please choose another slot."
            )

        new_apt = {
            "patient_id": user_id,
            "doctor_id": doctor_id,
            "hospital_id": payload.get("hospital_id"),
            "date": date_str,
            "time_slot": slot_str,
            "status": "Confirmed",
            "reason": payload.get("reason") or "General Health Consultation",
            "payment_method": payment_method_name,
            "payment_status": "Paid",
            "amount": payload.get("amount") or 500.0,
            "transaction_id": req.razorpay_payment_id,
            "razorpay_order_id": req.razorpay_order_id,
            "created_at": datetime.now()
        }

        apt_res = await db["appointments"].insert_one(new_apt)
        created_booking_id = str(apt_res.inserted_id)

        # Generate GST Invoice
        inv_number = f"INV-2026-{random.randint(10000, 99999)}"
        base_amt = float(payload.get("amount") or 500.0)
        tax_amt = round(base_amt * 0.18, 2)
        total_amt = round(base_amt + tax_amt, 2)

        doctor_name = "Doctor Specialist"
        try:
            doc_user = await db["users"].find_one({"_id": ObjectId(doctor_id)})
            if doc_user:
                doctor_name = doc_user.get("name", "Doctor Specialist")
        except Exception:
            pass

        patient_name = current_user.get("name") or "Patient"

        created_invoice_doc = {
            "invoice_number": inv_number,
            "user_id": user_id,
            "patient_name": patient_name,
            "patient_id": f"PAT-{(user_id[:6]).upper()}",
            "doctor_name": doctor_name if doctor_name.startswith("Dr.") else f"Dr. {doctor_name}",
            "doctor_specialization": payload.get("doctor_specialty") or "General Physician",
            "hospital_name": payload.get("hospital_name") or "Sehat-Sathi Care Clinic",
            "service_name": "Doctor Consultation & Health Guidance",
            "base_amount": base_amt,
            "tax_rate": 18.0,
            "tax_amount": tax_amt,
            "discount": 0.0,
            "total_amount": total_amt,
            "payment_method": payment_method_name,
            "payment_status": "Paid",
            "reference_number": req.razorpay_payment_id,
            "transaction_id": req.razorpay_payment_id,
            "founder_name": "Amit Dubey",
            "company_name": "Sehat-Sathi",
            "company_url": "www.sehatsathi.com",
            "created_at": datetime.now()
        }

        inv_res = await db["invoices"].insert_one(created_invoice_doc)
        created_invoice_doc["id"] = str(inv_res.inserted_id)
        created_invoice_doc.pop("_id", None)

        # Update payment record with invoice ID
        await db["payments"].update_one(
            {"order_id": req.razorpay_order_id},
            {"$set": {"appointment_id": created_booking_id, "invoice_id": created_invoice_doc["id"]}}
        )

        # Dispatch Notifications
        await _notify(
            db, user_id, "appointment_booked",
            "Payment Confirmed & Appointment Booked 🎉",
            f"Your appointment with {doctor_name} on {date_str} at {slot_str} is confirmed (Paid via Razorpay).",
            {"appointment_id": created_booking_id, "payment_id": req.razorpay_payment_id}
        )

        if doctor_id and len(doctor_id) == 24:
            await _notify(
                db, doctor_id, "appointment_booked",
                "New Paid Appointment Booking 📅",
                f"{patient_name} booked an appointment for {date_str} at {slot_str} (Paid via Razorpay).",
                {"appointment_id": created_booking_id}
            )

    elif booking_type == "room":
        # Hospital Room Reservation
        hosp_id = payload.get("hospital_id")
        days = max(1, int(payload.get("duration_days") or 1))
        daily_rate = float(payload.get("daily_rate") or 1800.0)
        base_amt = round(daily_rate * days, 2)
        tax_amt = round(base_amt * 0.18, 2)
        total_amt = round(base_amt + tax_amt, 2)

        room_booking_doc = {
            "user_id": user_id,
            "hospital_id": hosp_id,
            "hospital_name": payload.get("hospital_name") or "Sehat-Sathi Care Hospital",
            "room_type": payload.get("room_type") or "Semi-Private Room",
            "daily_rate": daily_rate,
            "duration_days": days,
            "admission_date": payload.get("admission_date"),
            "patient_name": payload.get("patient_name"),
            "patient_age": payload.get("patient_age"),
            "patient_gender": payload.get("patient_gender"),
            "contact_phone": payload.get("contact_phone"),
            "attendant_name": payload.get("attendant_name"),
            "reason": payload.get("reason"),
            "base_amount": base_amt,
            "tax_amount": tax_amt,
            "total_amount": total_amt,
            "payment_method": payment_method_name,
            "payment_status": "Paid",
            "transaction_id": req.razorpay_payment_id,
            "razorpay_order_id": req.razorpay_order_id,
            "status": "Confirmed",
            "created_at": datetime.now()
        }

        rb_res = await db["hospital_room_bookings"].insert_one(room_booking_doc)
        created_booking_id = str(rb_res.inserted_id)

        # Invoice
        inv_number = f"INV-ROOM-2026-{random.randint(10000, 99999)}"
        created_invoice_doc = {
            "invoice_number": inv_number,
            "user_id": user_id,
            "patient_name": payload.get("patient_name"),
            "patient_id": f"PAT-{(user_id[:6]).upper()}",
            "doctor_name": f"{payload.get('room_type')} Inpatient Team",
            "doctor_specialization": "Inpatient Hospital Care",
            "hospital_name": payload.get("hospital_name") or "Sehat-Sathi Care Hospital",
            "service_name": f"Hospital Room Reservation ({payload.get('room_type')} - {days} Days)",
            "base_amount": base_amt,
            "tax_rate": 18.0,
            "tax_amount": tax_amt,
            "discount": 0.0,
            "total_amount": total_amt,
            "payment_method": payment_method_name,
            "payment_status": "Paid",
            "reference_number": req.razorpay_payment_id,
            "transaction_id": req.razorpay_payment_id,
            "founder_name": "Amit Dubey",
            "company_name": "Sehat-Sathi",
            "company_url": "www.sehatsathi.com",
            "created_at": datetime.now()
        }
        inv_res = await db["invoices"].insert_one(created_invoice_doc)
        created_invoice_doc["id"] = str(inv_res.inserted_id)

    elif booking_type == "lab":
        # Diagnostic Lab Booking
        lab_id = payload.get("lab_id")
        base_amt = float(payload.get("base_amount") or 500.0)
        home_fee = float(payload.get("home_collection_fee") or 0.0)
        tax_amt = round((base_amt + home_fee) * 0.18, 2)
        total_amt = round(base_amt + home_fee + tax_amt, 2)

        lab_booking_doc = {
            "user_id": user_id,
            "lab_id": lab_id,
            "lab_name": payload.get("lab_name") or "Sehat-Sathi Pathology Lab",
            "tests": payload.get("tests") or [],
            "collection_type": payload.get("collection_type") or "Home Sample Collection",
            "sample_date": payload.get("sample_date"),
            "time_slot": payload.get("time_slot"),
            "patient_name": payload.get("patient_name"),
            "patient_age": payload.get("patient_age"),
            "patient_gender": payload.get("patient_gender"),
            "contact_phone": payload.get("contact_phone"),
            "collection_address": payload.get("collection_address"),
            "base_amount": base_amt,
            "home_collection_fee": home_fee,
            "tax_amount": tax_amt,
            "total_amount": total_amt,
            "payment_method": payment_method_name,
            "payment_status": "Paid",
            "transaction_id": req.razorpay_payment_id,
            "razorpay_order_id": req.razorpay_order_id,
            "status": "Booked",
            "created_at": datetime.now()
        }

        lb_res = await db["lab_bookings"].insert_one(lab_booking_doc)
        created_booking_id = str(lb_res.inserted_id)

        inv_number = f"INV-LAB-2026-{random.randint(10000, 99999)}"
        created_invoice_doc = {
            "invoice_number": inv_number,
            "user_id": user_id,
            "patient_name": payload.get("patient_name"),
            "patient_id": f"PAT-{(user_id[:6]).upper()}",
            "doctor_name": payload.get("lab_name") or "Pathology Diagnostics Team",
            "doctor_specialization": "Diagnostic Laboratory Tests",
            "hospital_name": payload.get("lab_name") or "Sehat-Sathi Partnered Lab",
            "service_name": f"Diagnostic Lab Tests ({payload.get('collection_type')})",
            "base_amount": base_amt + home_fee,
            "tax_rate": 18.0,
            "tax_amount": tax_amt,
            "discount": 0.0,
            "total_amount": total_amt,
            "payment_method": payment_method_name,
            "payment_status": "Paid",
            "reference_number": req.razorpay_payment_id,
            "transaction_id": req.razorpay_payment_id,
            "founder_name": "Amit Dubey",
            "company_name": "Sehat-Sathi",
            "company_url": "www.sehatsathi.com",
            "created_at": datetime.now()
        }
        inv_res = await db["invoices"].insert_one(created_invoice_doc)
        created_invoice_doc["id"] = str(inv_res.inserted_id)

    return {
        "success": True,
        "message": "Razorpay payment verified & booking confirmed!",
        "payment_id": req.razorpay_payment_id,
        "order_id": req.razorpay_order_id,
        "booking_id": created_booking_id,
        "invoice": created_invoice_doc
    }


# ─────────────────────────────────────────────────────────────
# 3. RAZORPAY WEBHOOK LISTENER
# ─────────────────────────────────────────────────────────────

@router.post("/webhook")
async def razorpay_webhook(
    request: Request,
    x_razorpay_signature: Optional[str] = Header(None, alias="X-Razorpay-Signature")
):
    """
    Asynchronous Webhook Listener for Razorpay.
    Verifies X-Razorpay-Signature against RAZORPAY_WEBHOOK_SECRET.
    Handles payment.captured, payment.failed, order.paid, refund.processed.
    """
    db = get_db()
    client = get_razorpay_client()

    raw_body = await request.body()
    body_str = raw_body.decode("utf-8")

    # Verify signature if webhook secret is configured
    if settings.RAZORPAY_WEBHOOK_SECRET and x_razorpay_signature:
        try:
            client.utility.verify_webhook_signature(
                body_str,
                x_razorpay_signature,
                settings.RAZORPAY_WEBHOOK_SECRET
            )
        except Exception as sig_err:
            raise HTTPException(status_code=400, detail=f"Webhook Signature Verification Failed: {str(sig_err)}")

    import json
    try:
        event_data = json.loads(body_str)
    except Exception:
        return {"status": "ignored", "reason": "invalid_json"}

    event = event_data.get("event")
    payload = event_data.get("payload", {})

    print(f"[WEBHOOK] Received Razorpay event: {event}")

    if event == "payment.captured":
        payment_obj = payload.get("payment", {}).get("entity", {})
        order_id = payment_obj.get("order_id")
        payment_id = payment_obj.get("id")
        method = (payment_obj.get("method") or "upi").upper()

        if order_id:
            await db["payments"].update_one(
                {"order_id": order_id},
                {"$set": {
                    "payment_id": payment_id,
                    "status": "captured",
                    "payment_method": method,
                    "webhook_processed_at": datetime.now()
                }}
            )

    elif event == "payment.failed":
        payment_obj = payload.get("payment", {}).get("entity", {})
        order_id = payment_obj.get("order_id")
        error_desc = payment_obj.get("error_description", "Payment Failed")

        if order_id:
            await db["payments"].update_one(
                {"order_id": order_id},
                {"$set": {
                    "status": "failed",
                    "failure_reason": error_desc,
                    "webhook_processed_at": datetime.now()
                }}
            )

    elif event == "refund.processed":
        refund_obj = payload.get("refund", {}).get("entity", {})
        payment_id = refund_obj.get("payment_id")
        refund_id = refund_obj.get("id")

        if payment_id:
            await db["payments"].update_one(
                {"payment_id": payment_id},
                {"$set": {
                    "status": "refunded",
                    "refund_id": refund_id,
                    "webhook_processed_at": datetime.now()
                }}
            )

    return {"status": "ok", "event": event}


# ─────────────────────────────────────────────────────────────
# 4. REFUND ENDPOINT
# ─────────────────────────────────────────────────────────────

@router.post("/refund/{payment_id}")
async def initiate_refund(
    payment_id: str,
    req: RefundRequest,
    current_user: dict = Depends(verify_token)
):
    """
    Initiates full or partial refund via Razorpay Refund API.
    Updates payments, appointments, and invoices.
    Restricted to Doctor, Hospital, or Admin role.
    """
    db = get_db()
    user_id = current_user.get("sub")
    role = current_user.get("role")
    client = get_razorpay_client()

    payment_record = await db["payments"].find_one({"payment_id": payment_id})
    if not payment_record and role not in ["Admin", "Doctor", "Hospital"]:
        raise HTTPException(status_code=403, detail="Unauthorized to refund this payment")

    refund_data = {}
    if req.amount:
        refund_data["amount"] = int(round(req.amount * 100))

    try:
        refund_res = client.payment.refund(payment_id, refund_data)
        refund_id = refund_res.get("id")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Razorpay Refund Error: {str(e)}")

    # Update payment status
    await db["payments"].update_one(
        {"payment_id": payment_id},
        {"$set": {
            "status": "refunded",
            "refund_id": refund_id,
            "refund_amount": req.amount or payment_record.get("amount"),
            "refund_reason": req.reason,
            "updated_at": datetime.now()
        }}
    )

    # Cancel associated appointment if any
    apt_id = payment_record.get("appointment_id") if payment_record else None
    if apt_id:
        try:
            await db["appointments"].update_one(
                {"_id": ObjectId(apt_id)},
                {"$set": {"status": "Cancelled", "payment_status": "Refunded", "cancelled_at": datetime.now()}}
            )
        except Exception:
            pass

    return {
        "success": True,
        "message": f"Refund initiated successfully! Refund ID: {refund_id}",
        "refund_id": refund_id,
        "payment_id": payment_id
    }


# ─────────────────────────────────────────────────────────────
# 5. TRANSACTION HISTORY & AUDIT LOG
# ─────────────────────────────────────────────────────────────

@router.get("/history")
async def get_payment_history(current_user: dict = Depends(verify_token)):
    """Fetch user's transaction audit log."""
    db = get_db()
    user_id = current_user.get("sub")

    cursor = db["payments"].find({"user_id": user_id}).sort("created_at", -1)
    payments = await cursor.to_list(length=100)
    for p in payments:
        p["id"] = str(p["_id"])
        p.pop("_id", None)
        if isinstance(p.get("created_at"), datetime):
            p["created_at"] = p["created_at"].isoformat()
        if isinstance(p.get("updated_at"), datetime):
            p["updated_at"] = p["updated_at"].isoformat()
    return payments


@router.get("/{payment_id}")
async def get_payment_by_id(payment_id: str, current_user: dict = Depends(verify_token)):
    """Get single payment details by Razorpay Payment ID or ObjectId."""
    db = get_db()
    
    pay = await db["payments"].find_one({
        "$or": [{"payment_id": payment_id}, {"order_id": payment_id}]
    })

    if not pay:
        try:
            pay = await db["payments"].find_one({"_id": ObjectId(payment_id)})
        except Exception:
            pass

    if not pay:
        raise HTTPException(status_code=404, detail="Payment transaction not found")

    pay["id"] = str(pay["_id"])
    pay.pop("_id", None)
    return pay
